### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by gepr** [BioSystemsGroup/bsg#3]
Andrew reports this:
Some of my simulations have stopped with "Too many open files". The following is the relevant section from the log file:

Exception in thread "MASON Model: class isl.measurement.view.BatchControl" java.lang.RuntimeException: java.io.FileNotFoundException: /home/android/Research/test/islj/build/classes/isl/model/bind-prob-function.js (Too many open files)
at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:397)
at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:446)
at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:403)
at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:399)
at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:233)
at bsg.util.ScriptEval.eval(ScriptEval.java:37)
at isl.model.Cell.getBindingProbability(Cell.java:139)

The code evals "load("+scriptLocation+")" each time it's called.  This probably opens a resource each time.  A better approach would be to define functions inside the script scope with a single engine.eval(script,scope) in the ScriptEval constructor, then each subsequent scriptEval.eval() call will simply call that function.  This makes the script functionality static over the course of the trial, which may limit us later.  But for now, we don't change it and may as well make it static.

Perhaps a better option would be to explicitly "close" the resource after each eval().

**Comment by gepr** [comment]
while true; do lsof -p &lt;jvmprocess&gt; | grep bind-prob | wc -l; sleep 20; done
shows the resources seem to be freed eventually, perhaps even immediately after the eval() is called.  So, it's not likely the source of the surviving generations "leak".  However, the problem is that any process will open as many of the bind-prob-function.js resources as it needs to to run the binding for however many cells one has.  Lots of cell objects ⇒ lots of open files.  ∴ the best response is to open the file once, define a function to be called inside it, then call that function in the eval(). 

The dynamism could be regained by redefining the function (per class or per object) during the simulation, perhaps by versioning the JS defined function.  The process could call the function to get its version and if it wanted a different function, load a different script.

A per-class/static/singleton re-loading would change the function for everyone (all Cell objects) whereas a per-object scope would allow each Cell to load its own if it didn't like the one it already had.

**Comment by gepr** [comment]
Fixed in commit: bf0ee7db86fe5daa6587d0f39c6a573c577e9ab7
Scripts are now only loaded once and JS functions (e.g. eval() and init()) are called subsequently.
